### ISSUE TITLE
Einspaltige Unterschriftenliste

### ISSUE THREAD

**Issue by RiggioLuca00** [JulianFink01/seminarverwaltung#4]
Falls ein Seminar nur am Vormittag oder Nachmittag stattfindet, soll nur eine Unterschriftspalte vorhanden sein.
Derzeit wird immer eine Vormittags und Nachmittagsspalte erstellt, was auch passt wenn sich das Seminar über den ganzen Tag erstreckt.

**Comment by david-jpg-art** [comment]
Alles erledigt & getestet
