### ISSUE TITLE
Kalendereintrag

### ISSUE THREAD

**Issue by RiggioLuca00** [JulianFink01/seminarverwaltung#5]
Bei einer An- bzw. Abmeldung zu einem Seminar soll nicht nur eine Email als Bestätigung geschickt werden wie bisher, sondern es soll auch ein automatischer Eintrag in den Kalender gemacht werden oder etwas vergleichbares.

**Comment by TheArled** [comment]
Fixed!

**Comment by TheArled** [comment]
Fixed!
